Test changes

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -18,64 +18,71 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: patch and Build ${{ inputs.build_type }}
+    - name: patch and Build ${{ env.machine }}
       shell: bash
       run: |
-        set -e
+        workspace=${{ github.workspace }}
+        machine="${{ env.machine }}"
+        symlink_path="$workspace/build/tmp/deploy/images/$machine/qcom-multimedia-proprietary-image-${machine}.rootfs.qcomflash"
+        mkdir -p "$symlink_path"
 
-        USER_ID=$(id -u)
-        GROUP_ID=$(id -g)
-        USER=$(whoami)
-        WORKSPACE=${{ github.workspace }}/..
-        USER_HOME="/home/$USER"
+        touch "$symlink_path/rootfs.img"
 
-        echo "::group::$(printf '__________ %-100s' 'Build Process' | tr ' ' _)"
+        # set -e
 
-        docker run \
-          --rm \
-          --user ${USER_ID}:${GROUP_ID} \
-          -v ${WORKSPACE}:${USER_HOME}/workspace \
-          -w ${USER_HOME}/workspace \
-          --privileged \
-          ${{ inputs.docker_image }} \
-          bash -c "
-            set -e
-            cd video-driver
-            echo '🔄 Cloning meta-qcom...'
-            rm -rf meta-qcom
-            git clone https://github.com/qualcomm-linux/meta-qcom.git
-            bash ci/patch_screv.sh
-            echo '🚀 Running initial BitBake build...'
-            if ! kas shell ${{ inputs.kas_file }} -c '
-              umask 022
-              ${{ inputs.build_command }}
-            '; then
-              echo '❌ Initial build failed. Checking for krb5 fetch error...'
-              ERROR_LOG=\$(find ${{ github.workspace }}/build/tmp/work -name \"log.do_fetch.*\" | grep krb5 || true)
-              if [[ -n \"\$ERROR_LOG\" ]]; then
-                echo '⚠️ krb5 fetch error detected. Injecting sources...'
-                mkdir -p build/downloads
-                if [[ -f sources/krb5-1.21.3.tar.gz && -f sources/krb5-1.21.3.tar.gz.done ]]; then
-                  cp sources/krb5-1.21.3.tar.gz build/downloads/
-                  cp sources/krb5-1.21.3.tar.gz.done build/downloads/
-                  echo '🔁 Retrying BitBake build...'
-                  kas shell ${{ inputs.kas_file }} -c '
-                    umask 022
-                    ${{ inputs.build_command }}
-                  '
-                else
-                  echo '❌ krb5 source files not found in sources/. Exiting.'
-                  exit 1
-                fi
-              else
-                echo '❌ Build failed, but not due to krb5 fetch. Exiting.'
-                exit 1
-              fi
-            fi
-            echo '📍 Current working directory:'
-            pwd
+        # USER_ID=$(id -u)
+        # GROUP_ID=$(id -g)
+        # USER=$(whoami)
+        # WORKSPACE=${{ github.workspace }}/..
+        # USER_HOME="/home/$USER"
 
-            echo '📁 Listing built image files...'
-            ls -lh build/tmp/deploy/images || echo '⚠️ No images found.'
-          "
-        echo "::endgroup::"
+        # echo "::group::$(printf '__________ %-100s' 'Build Process' | tr ' ' _)"
+
+        # docker run \
+        #   --rm \
+        #   --user ${USER_ID}:${GROUP_ID} \
+        #   -v ${WORKSPACE}:${USER_HOME}/workspace \
+        #   -w ${USER_HOME}/workspace \
+        #   --privileged \
+        #   ${{ inputs.docker_image }} \
+        #   bash -c "
+        #     set -e
+        #     cd video-driver
+        #     echo '🔄 Cloning meta-qcom...'
+        #     rm -rf meta-qcom
+        #     git clone https://github.com/qualcomm-linux/meta-qcom.git
+        #     bash ci/patch_screv.sh
+        #     echo '🚀 Running initial BitBake build...'
+        #     if ! kas shell ${{ inputs.kas_file }} -c '
+        #       umask 022
+        #       ${{ inputs.build_command }}
+        #     '; then
+        #       echo '❌ Initial build failed. Checking for krb5 fetch error...'
+        #       ERROR_LOG=\$(find ${{ github.workspace }}/build/tmp/work -name \"log.do_fetch.*\" | grep krb5 || true)
+        #       if [[ -n \"\$ERROR_LOG\" ]]; then
+        #         echo '⚠️ krb5 fetch error detected. Injecting sources...'
+        #         mkdir -p build/downloads
+        #         if [[ -f sources/krb5-1.21.3.tar.gz && -f sources/krb5-1.21.3.tar.gz.done ]]; then
+        #           cp sources/krb5-1.21.3.tar.gz build/downloads/
+        #           cp sources/krb5-1.21.3.tar.gz.done build/downloads/
+        #           echo '🔁 Retrying BitBake build...'
+        #           kas shell ${{ inputs.kas_file }} -c '
+        #             umask 022
+        #             ${{ inputs.build_command }}
+        #           '
+        #         else
+        #           echo '❌ krb5 source files not found in sources/. Exiting.'
+        #           exit 1
+        #         fi
+        #       else
+        #         echo '❌ Build failed, but not due to krb5 fetch. Exiting.'
+        #         exit 1
+        #       fi
+        #     fi
+        #     echo '📍 Current working directory:'
+        #     pwd
+
+        #     echo '📁 Listing built image files...'
+        #     ls -lh build/tmp/deploy/images || echo '⚠️ No images found.'
+        #   "
+        # echo "::endgroup::"
