Adding the s3 uploader

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,3 @@
----
 name: _build
 
 on:
@@ -26,13 +25,60 @@ jobs:
     steps:
       - name: Build docker image
         id: docker_build
-        uses: qualcomm-linux-stg/video-driver/.github/actions/build_docker_image@video.qclinux.0.0
+        uses: qualcomm-linux-stg/video-driver/.github/actions/build_docker_image@test-workflow
 
       - uses: actions/checkout@v4
 
       - name: Build ${{ matrix.build_matrix.machine }}
-        uses: qualcomm-linux-stg/video-driver/.github/actions/build@video.qclinux.0.0
+        uses: qualcomm-linux-stg/video-driver/.github/actions/build@test-workflow
         with:
           docker_image: ${{ steps.docker_build.outputs.image_name }}
           kas_file: ${{ matrix.build_matrix.kas_file }}
           build_command: "bitbake qcom-multimedia-proprietary-image"
+
+      - name: Create file list for artifacts upload
+        run: |
+          workspace=${{ github.workspace }}
+          mkdir -p $workspace/artifacts
+          touch $workspace/artifacts/file_list.txt
+
+          machine="${{ matrix.build_matrix.machine }}"
+          image_path="$workspace/build/tmp/deploy/images/${machine}/qcom-multimedia-proprietary-image-${machine}.rootfs.qcomflash"
+
+          if [ -f "$image_path" ]; then
+            echo "$image_path" >> $workspace/artifacts/file_list.txt
+          else
+            echo "⚠️ Image not found: $image_path"
+          fi
+
+      - name: Configure AWS
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-west-2
+
+      - name: Upload artifacts to S3
+        id: upload-artifacts
+        uses: qualcomm-linux/video-driver//.github/actions/aws_s3_helper@main
+        with:
+          s3_bucket: qli-stg-video-gh-artifacts
+          local_file: ${{ github.workspace }}/artifacts/file_list.txt
+          mode: multi-upload
+
+      - name: Clean up
+        run: |
+          rm -rf ${{ github.workspace }}/artifacts
+          rm -rf ${{ github.workspace }}/build
+          rm -f ${{ github.workspace }}/modules.tar.xz
+
+      - name: Update summary
+        if: success() || failure()
+        shell: bash
+        run: |
+          if [ "${{ job.status }}" == "success" ]; then
+            summary=":heavy_check_mark: Build Success for ${{ matrix.build_matrix.machine }}"
+          else
+            summary=":x: Build Failed for ${{ matrix.build_matrix.machine }}"
+          fi
+          echo -e "<details><summary><i>Build Summary</i></summary>\n${summary}\n</details>" >> $GITHUB_STEP_SUMMARY
